
#ifndef QT_INPUTPROCESSOR_EXPORT_H
#define QT_INPUTPROCESSOR_EXPORT_H

#ifdef QT_INPUTPROCESSOR_STATIC_DEFINE
#  define QT_INPUTPROCESSOR_EXPORT
#  define QT_INPUTPROCESSOR_NO_EXPORT
#else
#  ifndef QT_INPUTPROCESSOR_EXPORT
#    ifdef qt_inputprocessor_EXPORTS
        /* We are building this library */
#      define QT_INPUTPROCESSOR_EXPORT 
#    else
        /* We are using this library */
#      define QT_INPUTPROCESSOR_EXPORT 
#    endif
#  endif

#  ifndef QT_INPUTPROCESSOR_NO_EXPORT
#    define QT_INPUTPROCESSOR_NO_EXPORT 
#  endif
#endif

#ifndef QT_INPUTPROCESSOR_DEPRECATED
#  define QT_INPUTPROCESSOR_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef QT_INPUTPROCESSOR_DEPRECATED_EXPORT
#  define QT_INPUTPROCESSOR_DEPRECATED_EXPORT QT_INPUTPROCESSOR_EXPORT QT_INPUTPROCESSOR_DEPRECATED
#endif

#ifndef QT_INPUTPROCESSOR_DEPRECATED_NO_EXPORT
#  define QT_INPUTPROCESSOR_DEPRECATED_NO_EXPORT QT_INPUTPROCESSOR_NO_EXPORT QT_INPUTPROCESSOR_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef QT_INPUTPROCESSOR_NO_DEPRECATED
#    define QT_INPUTPROCESSOR_NO_DEPRECATED
#  endif
#endif

#endif
